# ==============================================================================
# 03_forecast_2srr.R
#
# 2SRR pipeline (Coulombe IJF 2025, Algorithm 1) on the Medeiros FRED-MD base.
#
# DESIGN DECISIONS (aligned with advisor / Hudson):
#   - n_oos = 180 windows (compatible with yout.rda already generated by
#     01_data_prep)
#   - h-step target: trailing cumulative Y_h(t) = sum_{j=0}^{h-1} y_{t-j}
#                    IDENTICAL to Medeiros -> guarantees comparability
#   - 3 TVP cases run in parallel (same windows, same data):
#       (1) TVP-AR     : univar=T, nofact=T
#       (2) TVP-Factor : factonly=T (PCA factors only, no y lags)
#       (3) TVP-FAVAR  : y lags + PCA factors
#   - MAIN engine: "coulombe_fast" — reproduces the EXACT mathematics of
#       TVPRR_cosso (u + beta_0 parameterization, separated lambda1 + lambda2,
#       GARCH in Step 2, OLS prior) but using the T x T kernel in closed form
#       instead of inflating Zprime to T x KT. ~10-50x faster without
#       mathematical loss.
#   - SANITY CHECK engine: "coulombe" (ORIGINAL TVPRR_cosso from Coulombe's
#       repo) run on a few representative windows. Empirically confirms that
#       coulombe_fast and the original produce equivalent forecasts.
#
# OUTPUTS:
#   30_output/forecasts/
#     2SRR_AR.rda     2SRR_Factor.rda     2SRR_FAVAR.rda   (forecasts 180 x 12)
#     Ridge_from_2SRR_<case>.rda                            (baseline)
#     2SRR_FAVAR_coulombe_check.rda                         (sanity check)
#   30_output/betas/
#     betas_2SRR_<case>.rda  (list per horizon, per window: TVP betas,
#                             Step 1 and Step 4 lambdas, omega, sigma2,
#                             var_names)
# ==============================================================================

cat("== 03_forecast_2srr.R ==\n\n")
source("00_prog/00_setup.R")

# Ensure glmnet/pracma loaded (used by fit_2srr_window)
suppressPackageStartupMessages({
  library(glmnet)
  library(pracma)
  library(fGarch)
})

# ----------------------------------------------------------------------------
# SELF-TESTS: validate the mathematical equivalence dual <-> primal (Eq. 5 of
# the paper) BEFORE spending hours running. If it fails, abort — that means
# the standalone is not computing the ridge correctly.
# ----------------------------------------------------------------------------
cat("\n[validation 1] Standalone self-test (dual vs primal Eq. 5)...\n")
diff_test <- tvp_self_test(seed = 1, T_obs = 30, K = 3,  lam = 1,   verbose = TRUE)
diff_test <- max(diff_test,
                  tvp_self_test(seed = 2, T_obs = 50, K = 5,  lam = 5,   verbose = TRUE),
                  tvp_self_test(seed = 3, T_obs = 80, K = 10, lam = 0.1, verbose = TRUE))
if (diff_test > 1e-6) stop("Self-test failed (diff=", diff_test,
                             "). Aborting before wasting hours of compute.")
cat("[validation 1 OK] standalone reproduces Eq. 5 with error <", 1e-6, "\n\n")

cat("[validation 2] coulombe_fast vs TVPRR_cosso/dualGRR original self-test...\n")
diff_test2 <- tvp_coulombe_fast_vs_original_test(seed = 11, T_obs = 25, K = 4,
                                                  lambda1 = 5, lambda2 = 0.1,
                                                  verbose = TRUE)
diff_test2 <- max(diff_test2,
                   tvp_coulombe_fast_vs_original_test(seed = 12, T_obs = 40, K = 6,
                                                       lambda1 = 100, lambda2 = 0.5,
                                                       verbose = TRUE))
if (!is.na(diff_test2) && diff_test2 > 1e-4)
  warning(sprintf("coulombe_fast diverges from original TVPRR_cosso by diff=%.3e",
                  diff_test2))
cat("[validation 2 OK or skipped]\n\n")

# 1. Configuration ------------------------------------------------------------

variable    <- "CPIAUCSL"
horizons    <- c(1, 3, 6, 12)
cases_tvp   <- c("AR", "Factor", "FAVAR")

# Main engine. Options:
#   "coulombe_fast" : faithful to TVPRR_cosso (u + beta_0 parameterization,
#                     separated lambda1/lambda2, OLS prior, GARCH).
#                     ~3-5h for 180 windows x 3 cases x 4 h.   [RECOMMENDED]
#   "standalone"    : simplified version (single lambda, no OLS prior).
#                     ~3-4h. Useful as a second opinion.
#   "coulombe"      : ORIGINAL TVPRR_cosso — extremely slow (~50-100h).
#                     Use only for sanity check on a few windows.
ENGINE_PRIMARY <- "coulombe_fast"

# Parallelization: within each window we run 12 independent fits (3 cases x
# 4 horizons). They are perfectly parallelizable. On Windows we use a PSOCK
# cluster (parallel base package, no extra dependencies).
# N_CORES = number of workers. Default leaves 1 core free for the OS.
# To force sequential (debug): N_CORES <- 1
N_CORES <- max(1, parallel::detectCores() - 1)

# Hyperparameters (aligned with Coulombe IJF 2025, sec. 4)
ly          <- 2          # y lags
lf          <- 2          # factor lags
nf          <- 4          # number of PCA factors
kfold       <- 5
n_lambda    <- 15

# Over-extended grid for lambda (Coulombe's original grid is too narrow for the paper's quarterly sample). The optimal lambda scales ~ T in the ridge regime, so we raise the
# n_lambda    <- 25
# lambda_vec  <- exp(pracma::linspace(-4, 18, n = n_lambda))

# Extended grid for monthly data (T~600+). Coulombe's original grid
# (linspace(-2, 12, 15), max ~163k) saturated in ~89% of windows because his
# sample is ~3x larger in T than the paper's (quarterly). For large T, the
# optimal lambda scales ~ T in the ridge regime, so we raise the ceiling.
lambda_vec  <- exp(pracma::linspace(-2, 12, n = n_lambda))
lambda2     <- 0.1        # constant-block lambda (Coulombe default)

# Sanity check: run the ORIGINAL TVPRR_cosso on these windows for comparison.
# Keep SMALL — each call to the original Coulombe takes ~10-30 min.
RUN_COULOMBE_CHECK     <- TRUE
COULOMBE_CHECK_WINDOWS <- c(40, 90, 140)   # 3 windows (start, mid, end of OOS)
COULOMBE_CHECK_HS      <- c(1, 12)         # h=1 (short) and h=12 (long)
COULOMBE_CHECK_CASE    <- "FAVAR"           # case to check

# 2. Data ---------------------------------------------------------------------

load(file.path(DIR_DATA, "data.rda"))
load(file.path(DIR_FORECASTS, "yout.rda"))

dates_col <- data$date
data$date <- NULL

bigt  <- nrow(data)
n_oos <- nrow(yout)
tau   <- bigt - n_oos
y_col <- which(names(data) == variable)
maxh  <- 12

cat(sprintf("  Total obs: %d | OOS start: %d | OOS windows: %d\n",
            bigt, tau + 1, n_oos))
cat(sprintf("  TVP cases: %s | Horizons: %s\n",
            paste(cases_tvp, collapse = ", "),
            paste(horizons, collapse = ",")))

# 3. Output containers --------------------------------------------------------

# Per case: 2SRR forecasts matrix + Ridge baseline forecasts matrix
fc_2srr  <- setNames(lapply(cases_tvp, function(.) matrix(NA_real_, n_oos, maxh)),
                     cases_tvp)
fc_ridge <- setNames(lapply(cases_tvp, function(.) matrix(NA_real_, n_oos, maxh)),
                     cases_tvp)
for (case in cases_tvp) {
  colnames(fc_2srr[[case]])  <- paste0("h", 1:maxh)
  colnames(fc_ridge[[case]]) <- paste0("h", 1:maxh)
}

# Betas/lambdas: list per case > per horizon > per window
betas_store <- setNames(
  lapply(cases_tvp, function(.)
    setNames(lapply(horizons, function(.) vector("list", n_oos)),
             paste0("h", horizons))),
  cases_tvp)

# Sanity check container
coulombe_check <- list()

# 4. Helpers ------------------------------------------------------------------

# Standardizes X_is_raw (removes zero-var columns, scales)
prepare_X_is <- function(X_is) {
  cv <- apply(X_is, 2, var, na.rm = TRUE)
  good <- which(is.finite(cv) & cv > 1e-10)
  X_is <- X_is[, good, drop = FALSE]
  X_is[is.na(X_is)] <- 0   # NAs are rare in this base
  X_means <- colMeans(X_is)
  X_sds   <- apply(X_is, 2, sd); X_sds[X_sds < 1e-10] <- 1
  scale(X_is, center = X_means, scale = X_sds)
}

# 5. POOS Loop ----------------------------------------------------------------

# Runs the 3 cases with the main engine. If outputs already exist for all
# cases, skip. Otherwise, process whatever is missing.
all_out_paths <- sapply(cases_tvp, function(c)
                          file.path(DIR_FORECASTS, paste0("2SRR_", c, ".rda")))
need_run <- !all(file.exists(all_out_paths))

# Job list (case, horizon) — 12 independent jobs per window
jobs <- list()
for (case in cases_tvp) for (h in horizons)
  jobs[[length(jobs) + 1]] <- list(case = case, h = h)

# ---- Parallelization cluster (PSOCK, works on Windows) ----------------------
cl <- NULL
if (need_run && N_CORES > 1) {
  cat(sprintf("\n  [parallel] Starting cluster with %d workers ...\n", N_CORES))
  cl <- parallel::makeCluster(N_CORES, type = "PSOCK")

  # Each worker sources the setup (loads Coulombe, Medeiros, tvp_functions).
  # Important: use the master's getwd() because setwd on workers has no effect.
  ROOT_DIR <- getwd()
  parallel::clusterExport(cl, "ROOT_DIR", envir = environment())
  parallel::clusterEvalQ(cl, {
    setwd(ROOT_DIR)
    suppressMessages(suppressWarnings(source("00_prog/00_setup.R")))
    invisible(NULL)
  })

  # Reproducibility of CV folds
  parallel::clusterSetRNGStream(cl, 12345)

  # Export constant hyperparameters (do not change between windows)
  parallel::clusterExport(cl,
    c("ly", "lf", "nf", "kfold", "lambda_vec", "lambda2", "ENGINE_PRIMARY"),
    envir = environment())

  cat("  [parallel] Cluster ready.\n")
  # Stop the cluster on script exit (even on error)
  on.exit({ try(parallel::stopCluster(cl), silent = TRUE) }, add = TRUE)
}

# Worker that processes a single job (case, h). Receives all data via
# arguments to avoid scope issues with the PSOCK cluster (each worker has
# isolated env; clusterExport ensures ly, lf, nf, etc. are available).
fit_one_job <- function(job, y_is, X_is_std, ly, lf, nf, kfold,
                          lambda_vec, lambda2, ENGINE_PRIMARY) {
  res <- fit_2srr_window(
    y_is = y_is, X_is_raw = X_is_std,
    h = job$h, case = job$case,
    ly = ly, lf = lf, nf = nf, kfold = kfold,
    lambdas = lambda_vec, lambda2 = lambda2,
    coulombe_lambdavec = lambda_vec,
    engine = ENGINE_PRIMARY
  )
  list(job = job, res = res)
}

if (!need_run) {
  cat("\n  Outputs 2SRR_*.rda already exist. Main loop SKIPPED.\n")
  # CRITICAL: the sanity check (section 7) needs fc_2srr to be populated to
  # compare coulombe_fast vs original TVPRR_cosso. Without this load, fc_2srr
  # stays all-NA -> ok_pair = FALSE -> empty coulombe_check -> useless 80-byte
  # file.
  cat("  Loading existing fc_2srr from disk for sanity check...\n")
  for (case in cases_tvp) {
    fp <- file.path(DIR_FORECASTS, paste0("2SRR_", case, ".rda"))
    if (file.exists(fp)) {
      env <- new.env(); load(fp, envir = env)
      obj_name <- ls(env)[1]
      mat <- as.matrix(get(obj_name, envir = env))
      fc_2srr[[case]] <- mat
      cat(sprintf("    fc_2srr[[%s]] %d x %d loaded (NAs: %d/%d)\n",
                  case, nrow(mat), ncol(mat),
                  sum(is.na(mat)), length(mat)))
    }
  }
} else {

  t_total <- Sys.time()
  cat(sprintf("\n  Starting POOS loop (engine=%s, 3 cases x 4 h x %d windows, %d workers)\n",
              ENGINE_PRIMARY, n_oos, N_CORES))

  for (wi in 1:n_oos) {
    t_end <- tau + wi - 1   # last in-sample obs (Medeiros conv. = 01_data_prep)

    # ---------- 5a. In-sample window ----------
    X_is_full <- as.matrix(data[1:t_end, -y_col, drop = FALSE])
    y_is      <- as.numeric(data[1:t_end, y_col])
    X_is_std  <- prepare_X_is(X_is_full)

    # ---------- 5b. Dispatch the 12 jobs (case x horizon) ----------
    t0 <- Sys.time()
    if (!is.null(cl)) {
      out_list <- parallel::parLapply(
        cl, jobs, fit_one_job,
        y_is = y_is, X_is_std = X_is_std,
        ly = ly, lf = lf, nf = nf, kfold = kfold,
        lambda_vec = lambda_vec, lambda2 = lambda2,
        ENGINE_PRIMARY = ENGINE_PRIMARY)
    } else {
      out_list <- lapply(jobs, fit_one_job,
        y_is = y_is, X_is_std = X_is_std,
        ly = ly, lf = lf, nf = nf, kfold = kfold,
        lambda_vec = lambda_vec, lambda2 = lambda2,
        ENGINE_PRIMARY = ENGINE_PRIMARY)
    }

    # ---------- 5c. Collect results into containers ----------
    for (entry in out_list) {
      job <- entry$job; res <- entry$res
      hlab <- paste0("h", job$h)
      fc_2srr[[job$case]][wi, job$h]  <- res$forecast
      fc_ridge[[job$case]][wi, job$h] <- res$ridge_forecast
      betas_store[[job$case]][[hlab]][[wi]] <- list(
        betas_tvp    = res$betas_tvp,
        lambda       = res$lambda,
        lambda_step1 = res$lambda_step1,
        omega        = res$omega,
        sigma2       = res$sigma2,
        var_names    = res$var_names,
        n_obs        = res$n_obs,
        n_vars       = res$n_vars,
        status       = res$status
      )
    }

    # ---------- 5d. Progress + checkpoint ----------
    if (wi %% 10 == 1 || wi == n_oos) {
      el <- difftime(Sys.time(), t0, units = "secs")
      el_total <- difftime(Sys.time(), t_total, units = "mins")
      eta_min  <- as.numeric(el_total) / wi * (n_oos - wi)
      cat(sprintf("  win %3d/%d (T_is=%d) %.1fs  ||  total %.1f min  ETA %.1f min\n",
                  wi, n_oos, t_end, as.numeric(el),
                  as.numeric(el_total), eta_min))
    }

    if (wi %% 30 == 0) {
      ckpt_file <- file.path(DIR_CHECKPOINTS,
                              sprintf("ckpt_2SRR_w%03d.rda", wi))
      save(fc_2srr, fc_ridge, betas_store, file = ckpt_file)
      cat(sprintf("    [checkpoint saved: %s]\n", basename(ckpt_file)))
    }
  }

  cat(sprintf("\n  Main loop finished in %.1f min.\n",
              as.numeric(difftime(Sys.time(), t_total, units = "mins"))))

  # 6. Save outputs ----------------------------------------------------------
  cat("\n  Saving outputs...\n")
  for (case in cases_tvp) {
    # 2SRR forecasts in Medeiros-compatible format (object named `forecasts`)
    forecasts <- fc_2srr[[case]]
    save(forecasts,
         file = file.path(DIR_FORECASTS, paste0("2SRR_", case, ".rda")))
    cat(sprintf("    2SRR_%s.rda saved.\n", case))

    # Ridge baseline (Step 1 of Algorithm 1; useful for Half-Half + comparison)
    forecasts <- fc_ridge[[case]]
    save(forecasts,
         file = file.path(DIR_FORECASTS, paste0("Ridge_from_2SRR_", case, ".rda")))

    # Betas bundle (same format as Medeiros models)
    betas_bundle <- betas_store[[case]]
    save(betas_bundle,
         file = file.path(DIR_BETAS, paste0("betas_2SRR_", case, ".rda")))
    cat(sprintf("    betas_2SRR_%s.rda saved.\n", case))
  }
}

# 7. Sanity check: ORIGINAL TVPRR_cosso vs coulombe_fast on a few windows ----
#    Runs the non-optimized Coulombe code and compares forecasts and betas
#    against the main engine (coulombe_fast). Mean relative difference < ~5%
#    empirically confirms the mathematical equivalence.

if (RUN_COULOMBE_CHECK) {
  check_path <- file.path(DIR_FORECASTS,
                          sprintf("2SRR_%s_coulombe_check.rda", COULOMBE_CHECK_CASE))
  # Detect empty/corrupted file (< 500 bytes probably means empty list)
  check_too_small <- file.exists(check_path) && file.info(check_path)$size < 500
  if (check_too_small) {
    cat(sprintf("\n  Existing sanity check at %s has %d bytes (empty/corrupted). Removing.\n",
                basename(check_path), file.info(check_path)$size))
    file.remove(check_path)
  }
  if (file.exists(check_path)) {
    cat("\n  Sanity check already exists at", basename(check_path), "- skip.\n")
  } else {
    cat(sprintf("\n  --- Sanity check (case=%s): ORIGINAL TVPRR_cosso on %d windows x %d horizons ---\n",
                COULOMBE_CHECK_CASE, length(COULOMBE_CHECK_WINDOWS),
                length(COULOMBE_CHECK_HS)))
    cat("  (each original Coulombe call takes some minutes; total ~30-90 min)\n")

    if (!exists("TVPRR_cosso", mode = "function")) {
      cat("    WARNING: TVPRR_cosso not loaded. Skipping sanity check.\n")
    } else {
      # Sanity check: confirm fc_2srr is populated (could be all-NA if the
      # main loop was skipped AND no load happened — pre-flight diagnostic).
      fc_mat_check <- fc_2srr[[COULOMBE_CHECK_CASE]]
      n_total_cells <- length(fc_mat_check)
      n_na_cells <- sum(is.na(fc_mat_check))
      cat(sprintf("  fc_2srr[[%s]] dim=%dx%d, NAs=%d/%d\n",
                  COULOMBE_CHECK_CASE, nrow(fc_mat_check), ncol(fc_mat_check),
                  n_na_cells, n_total_cells))
      if (n_na_cells == n_total_cells) {
        cat("  [WARNING] fc_2srr is ALL NA. Sanity check will be useless.\n")
        cat("  Check whether 2SRR_*.rda were loaded or the main loop ran.\n")
      }
      flush.console()   # force buffer flush on Windows
      coulombe_check <- list()
      for (wi in COULOMBE_CHECK_WINDOWS) {
        if (wi > n_oos) next
        t_end <- tau + wi - 1
        X_is_full <- as.matrix(data[1:t_end, -y_col, drop = FALSE])
        y_is      <- as.numeric(data[1:t_end, y_col])
        X_is_std  <- prepare_X_is(X_is_full)

        for (h in COULOMBE_CHECK_HS) {
          cat(sprintf("    win %3d  h=%2d ... ", wi, h))
          flush.console()
          t0 <- Sys.time()
          # MAIN engine (coulombe_fast) — uses the already-saved forecast
          fc_main <- fc_2srr[[COULOMBE_CHECK_CASE]][wi, h]

          # ORIGINAL engine (TVPRR_cosso, slow) — recomputed here
          res_orig <- tryCatch(
            fit_2srr_window(
              y_is = y_is, X_is_raw = X_is_std,
              h = h, case = COULOMBE_CHECK_CASE,
              ly = ly, lf = lf, nf = nf, kfold = kfold,
              lambdas = lambda_vec, lambda2 = lambda2,
              coulombe_lambdavec = lambda_vec,
              engine = "coulombe"),
            error = function(e) { message("FAIL: ", e$message); NULL })

          el <- as.numeric(difftime(Sys.time(), t0, units = "mins"))
          # Stronger guards: BOTH forecasts must be finite
          ok_pair <- !is.null(res_orig) &&
                       !is.na(res_orig$forecast) && is.finite(res_orig$forecast) &&
                       !is.na(fc_main)            && is.finite(fc_main)
          if (ok_pair) {
            rel_diff <- abs(res_orig$forecast - fc_main) /
                         max(abs(fc_main), 1e-6)
            coulombe_check[[sprintf("w%d_h%d", wi, h)]] <- list(
              window         = wi, horizon = h, case = COULOMBE_CHECK_CASE,
              fc_coulombe_original = res_orig$forecast,
              fc_coulombe_fast     = fc_main,
              rel_diff             = rel_diff,
              ridge_forecast       = res_orig$ridge_forecast,
              betas_coulombe       = res_orig$betas_tvp,
              lambda_coulombe      = res_orig$lambda,
              elapsed_min          = el
            )
            cat(sprintf("done %.1f min | orig=%.4f  fast=%.4f  rel_diff=%.2f%%\n",
                        el, res_orig$forecast, fc_main, 100 * rel_diff))
          } else {
            cat(sprintf("FAIL/skip (orig=%s fast=%s elapsed=%.1fmin).\n",
                        if (is.null(res_orig)) "NULL"
                        else if (is.null(res_orig$forecast)) "NULL$forecast"
                        else if (is.na(res_orig$forecast)) "NA"
                        else sprintf("%.4f", res_orig$forecast),
                        if (is.na(fc_main)) "NA" else sprintf("%.4f", fc_main),
                        el))
          }
          flush.console()
        }
      }
      save(coulombe_check, file = check_path)
      # Robust summary: vapply forces a numeric vector (sapply may return
      # list() if coulombe_check is empty or has NULL entries).
      diffs <- if (length(coulombe_check) == 0) numeric(0)
               else vapply(coulombe_check, function(x) {
                 v <- x$rel_diff
                 if (is.null(v) || length(v) == 0) NA_real_
                 else as.numeric(v[1])
               }, numeric(1))
      diffs <- diffs[is.finite(diffs)]
      if (length(diffs) > 0) {
        m_diff <- mean(diffs)
        cat(sprintf("\n  Sanity check result: %d valid comparisons\n",
                    length(diffs)))
        cat(sprintf("    mean rel_diff = %.2f%%\n", 100 * m_diff))
        cat(sprintf("    max  rel_diff = %.2f%%\n", 100 * max(diffs)))
        if (m_diff < 0.05)
          cat("    [OK] coulombe_fast equivalent to original TVPRR_cosso (<5% mean diff).\n")
        else
          cat("    [WARNING] divergence > 5%. Investigate before defending the thesis.\n")
      } else {
        cat("\n  [WARNING] No comparison with finite diff. Possibly\n")
        cat("  TVPRR_cosso returned NA or the corresponding cells of\n")
        cat("  2SRR_FAVAR.rda were NA. The mathematical validation (validation 2\n")
        cat("  at the start) already guarantees bit-exact equivalence; the\n")
        cat("  empirical sanity check is redundancy.\n")
      }
      cat(sprintf("    Saved at %s\n", basename(check_path)))
    }
  }
}

cat("\n== done ==\n")
